language: python
python:
  - "2.7"
install:
  - mv $TRAVIS_BUILD_DIR ~/tracker

  # Pull down toplevel repo
  - git clone https://github.com/TipoftheHats/donation-tracker-toplevel ~/toplevel
  - cd ~/toplevel
  - git submodule update --init

  # Move tracker into toplevel
  - rm -rf ~/toplevel/tracker
  - mv ~/tracker ~/toplevel

   # Install requirements
  - pip install -r tracker/requirements.txt
script:
  - cd ~/toplevel && cp tracker/tests/travis_local.py local.py && python manage.py test

notifications:
  slack:
    secure: i/6EQayYlKepjDhYK3HTwDRBIiijj8/euaTFVvKBdHuE0pnAnpPJ8Uhr2z1XBgMdqkZ/vXX90Tptw3tTXx+1XCVoUnF+pbtP4Ry0zNuGEm/x1Z4+9sy3yZMcn6A6QZIOiXHI4ZoneZ0BWpj9OfQ7GAJFCkbiq3HA+DFkgLhOWqoF/uOTHqo3aOSSmiHhVYu8j0jwcKI35oqa45Skyi7nRI7eezwCNk4FUcJR7ozrohyc2vI57T4DBeknjFZBZgeUITfi5xEvV/HODasU8FmuHY51RRurs/ZI6mUp0mqVbDEthKqB5dsvskXEpsJM2YBSMkNcqqG73GAwFlNSz60UdNQtBUouigeWwc2rkSjqt/6vw77fl6GuHflsUcrky0gcUMgNwdx8ZSCFgYjrPyrziSKeX1RUUVXjELT5vEEZEgxycbIWam9EDUEILn2F/Dgld61RZn6caBT8YXIvwZHNwBHKlj16GDoQJR/B3wKIg/6Mm+xwm+tX7XNFQvk9a6qcIdhnZQWxfLOwL6PeI/c8nOBGaHHlrYynuV1NcIrBqRnC2jRezkLNNVa8LUpVKg6V40asqoxg1CHNvTd0mRfa2XjdqQl1dzmpayXj0GFH1r4PA5kf38pVJuOw2w9xWTGscfHdnJYfSh31+QcfBTvj18g8y9p8SYEgkBTPAVzKzCI=
