# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-06 01:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_donor_cache_tweaks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ('alpha2',), 'verbose_name_plural': 'countries'},
        ),
        migrations.AlterField(
            model_name='donation',
            name='domain',
            field=models.CharField(choices=[('LOCAL', 'Local'), ('CHIPIN', 'ChipIn'), ('PAYPAL', 'PayPal'), ('SCRAPTF', 'Scrap.TF')], default='LOCAL', max_length=255),
        ),
        migrations.AlterField(
            model_name='donation',
            name='steamid',
            field=models.CharField(blank=True, max_length=64, verbose_name='SteamID 64'),
        ),
    ]
