# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-09-08 22:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_remove_event_date'),
        ('tracker', '0041_merge'),
    ]

    operations = [
    ]
